### ISSUE TITLE
NPE in wasliecore.handlers.events.OnEntityDamageEvent.onEntityDamage

### ISSUE THREAD

**Issue by Torins** [wasliebob/WaslieCore#2]
Hello, there seems to be a null pointer exception in WaslieCore 1.1 (build #41 from your Jenkins) when Thaumcraft Extras 2 (build #50) is used together with Lycanite Mobs 1.9.0 (and possibly Chocolate Quest 1.7.10-BETA2, but I didn't have the time to confirm what my friend told me).

Here's the crash log:

http://pastebin.com/1LL8PgAa

**Comment by wasliebob** [comment]
Seems like it's because LycaniteMobs is handeling entity damage incorrectly, cannot fix this sadly.

**Comment by wasliebob** [comment]
Might look at it, but most likely not on my side.
